# Generated by Django 2.2 on 2019-12-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191202_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=2, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
